/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

(* top =  1  *)
(* src = "bk4b.v:1.1-52.10" *)
module bk4b(A, B, Cin, Sum, Cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* src = "bk4b.v:2.14-2.15" *)
  wire _20_;
  (* src = "bk4b.v:2.14-2.15" *)
  wire _21_;
  (* src = "bk4b.v:2.14-2.15" *)
  wire _22_;
  (* src = "bk4b.v:2.14-2.15" *)
  wire _23_;
  (* src = "bk4b.v:2.17-2.18" *)
  wire _24_;
  (* src = "bk4b.v:2.17-2.18" *)
  wire _25_;
  (* src = "bk4b.v:2.17-2.18" *)
  wire _26_;
  (* src = "bk4b.v:2.17-2.18" *)
  wire _27_;
  (* src = "bk4b.v:3.8-3.11" *)
  wire _28_;
  (* src = "bk4b.v:5.9-5.13" *)
  wire _29_;
  (* src = "bk4b.v:4.15-4.18" *)
  wire _30_;
  (* src = "bk4b.v:4.15-4.18" *)
  wire _31_;
  (* src = "bk4b.v:4.15-4.18" *)
  wire _32_;
  (* src = "bk4b.v:4.15-4.18" *)
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  (* src = "bk4b.v:2.14-2.15" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "bk4b.v:2.17-2.18" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "bk4b.v:43.13-43.14" *)
  (* unused_bits = "1 2 3" *)
  wire [4:0] C;
  (* src = "bk4b.v:3.8-3.11" *)
  input Cin;
  wire Cin;
  (* src = "bk4b.v:5.9-5.13" *)
  output Cout;
  wire Cout;
  (* src = "bk4b.v:15.13-15.15" *)
  (* unused_bits = "0 1 2 3" *)
  wire [3:0] G0;
  (* src = "bk4b.v:21.13-21.15" *)
  (* unused_bits = "0 1 2 3" *)
  wire [3:0] G1;
  (* src = "bk4b.v:32.13-32.15" *)
  (* unused_bits = "0 1 2" *)
  wire [3:0] G2;
  (* src = "bk4b.v:4.15-4.18" *)
  output [3:0] Sum;
  wire [3:0] Sum;
  sky130_fd_sc_hd__xnor2_1 _42_ (
    .A(_26_),
    .B(_22_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__xnor2_1 _43_ (
    .A(_25_),
    .B(_21_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__maj3_1 _44_ (
    .A(_28_),
    .B(_20_),
    .C(_24_),
    .X(_36_)
  );
  sky130_fd_sc_hd__maj3_1 _45_ (
    .A(_25_),
    .B(_21_),
    .C(_36_),
    .X(_37_)
  );
  sky130_fd_sc_hd__maj3_1 _46_ (
    .A(_26_),
    .B(_22_),
    .C(_37_),
    .X(_38_)
  );
  sky130_fd_sc_hd__xnor2_1 _47_ (
    .A(_27_),
    .B(_23_),
    .Y(_39_)
  );
  sky130_fd_sc_hd__maj3_1 _48_ (
    .A(_27_),
    .B(_23_),
    .C(_38_),
    .X(_29_)
  );
  sky130_fd_sc_hd__nor3_1 _49_ (
    .A(_28_),
    .B(_20_),
    .C(_24_),
    .Y(_40_)
  );
  sky130_fd_sc_hd__nand3_1 _50_ (
    .A(_28_),
    .B(_20_),
    .C(_24_),
    .Y(_41_)
  );
  sky130_fd_sc_hd__o21ai_0 _51_ (
    .A1(_36_),
    .A2(_40_),
    .B1(_41_),
    .Y(_30_)
  );
  sky130_fd_sc_hd__xnor2_1 _52_ (
    .A(_35_),
    .B(_36_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__xnor2_1 _53_ (
    .A(_34_),
    .B(_37_),
    .Y(_32_)
  );
  sky130_fd_sc_hd__xnor2_1 _54_ (
    .A(_38_),
    .B(_39_),
    .Y(_33_)
  );
  assign { C[4], C[0] } = { Cout, Cin };
  assign G0[0] = C[1];
  assign G1[2:0] = { G0[2], C[2:1] };
  assign G2 = { Cout, C[3:1] };
  assign _27_ = B[3];
  assign _23_ = A[3];
  assign _26_ = B[2];
  assign _22_ = A[2];
  assign _25_ = B[1];
  assign _21_ = A[1];
  assign _28_ = Cin;
  assign _20_ = A[0];
  assign _24_ = B[0];
  assign Cout = _29_;
  assign Sum[0] = _30_;
  assign Sum[1] = _31_;
  assign Sum[2] = _32_;
  assign Sum[3] = _33_;
endmodule
